name: flutter_toolkit
description: M工具箱

version: 1.6.0+60

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # user_util:
  #   path: packages/user_util
  encrypt: ^4.0.0
  ffi: ^0.1.3
  sqflite: ^1.2.0
  video_player: ^0.10.2+3
  aeyrium_sensor: ^1.0.7
  convert: ^2.1.1
  # rotated_view: ^1.0.1
  flutter_spinkit: ^4.0.0
  event_bus: ^1.1.0
  path_provider: ^1.3.0
  draggable_scrollbar: ^0.0.4
  shimmer: ^1.0.0
  dio: ^3.0.3
  # extended_text_field: ^0.4.2
  flutter_icons: ^0.1.4
  provider: ^3.1.0
  share: ^0.6.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/
    - busybox

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: NotoSansCJK-Regular
  #     fonts:
  #       - asset: fonts/NotoSansCJK-Regular.ttf
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #         weight: 400
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
